[package]
name = "teh-o-prke"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
ndarray = "0.15.6"
ndarray-linalg = "0.16.0"
thiserror = "1.0.58"
uom = "0.36.0"
